apiVersion: v1
kind: Config
clusters:
- cluster:
    server: http://localhost:8000
  name: mock-cluster
contexts:
- context:
    cluster: mock-cluster
    user: mock-user
  name: mock-context
current-context: mock-context
preferences: {}
users:
- name: mock-user
